### ISSUE TITLE
Closing Session

### ISSUE THREAD

**Issue by shadrus** [szastupov/aiotg#37]
Some thinks about a way to close HttpSession.
[https://github.com/shadrus/aiotg/commit/c06c996fed03ed59f2c015061d8b0503f03a56fa](https://github.com/shadrus/aiotg/commit/c06c996fed03ed59f2c015061d8b0503f03a56fa)

**Comment by szastupov** [comment]
Unfortunately it doesn't solve the problem for getUpdates mode and we still get a warning for creating a session outside a coroutine.
