### ISSUE TITLE
Option to send chat action automatically.

### ISSUE THREAD

**Issue by MechanisM** [szastupov/aiotg#38]
It would be nice to have something in `_process_message` to send the `send_chat_action` before sending a message. Like if it was `chat.send_text()` or `chat.reply()`, we can send the `chat.send_chat_action('typing')` for sure automatically if it's enabled in bot's settings. The same for audio and photos... The same approach already is done for tracking to `botan`, but we can send chat actions as well. Also, it would be nice to have it enabled by default.
Currently, almost 30% of the code for my bot are chat actions lol.

**Comment by szastupov** [comment]
I guess I don't mind adding this feature as long as it is optional. Not sure which class should handle it though, Chat or Bot. Anyway, pull requests are welcome ;)
