### ISSUE TITLE
Additional callback_query data in CallbackQuery __init__

### ISSUE THREAD

**Issue by JustDolanIt** [szastupov/aiotg#46]
Hello!

In my project I need to get information about who pressed button in chat, but as I was looking at source code, I found out, that **\_\_init\_\_** method for **aiotg.bot.CallbackQuery** class is not saving some fields from __callback_query__ key that is sent to webhook.

What is already gatherable:
* message - may be gathered with Chat object
* id - saved in self.query_id
* data - saved in self.data

What is missing:
* chat_instance - not sure if required, according to docs needed in games (https://core.telegram.org/bots/api#callbackquery)
* from - usable, i.e. if you want to know who pressed button and want to tell in reply and show who was it

And there other fields from Telegram API docs, but not sure if usable:
* inline_message_id - haven't worked with inline messages, so can't say anything about it
* game_short_name - same here

I'm mostly interested in __from__ field, but for a general purposes it would be better if all those fields will be available

Also maybe it would be better if fields are generated dynamicly from existing keys of __callback_query__, so it wouldn't be required to make new changes in future.

**Comment by szastupov** [comment]
Hi, would this solve your problem? https://github.com/szastupov/aiotg/commit/b66efd5cf6f3df2e9b724f83fb5e247c5260f40d

**Comment by szastupov** [comment]
Actually, please take a look at this diff https://github.com/szastupov/aiotg/compare/pass_chat_to_cbq

**Comment by JustDolanIt** [comment]
I would rather just add src as object data field as i did here https://github.com/JustDolanIt/aiotg/commit/2d9a79530cabbb3062d3f68b24ba6c048d2a18c7
This way we will not brake backwards compatibility, but it will be possible to get all required data from stored dict

**Comment by szastupov** [comment]
Ok then, feel free to submit a Pull Request from this commit and I'll merge it 👌

**Comment by JustDolanIt** [comment]
https://github.com/szastupov/aiotg/pull/48

**Comment by szastupov** [comment]
Fixed by #48
