### ISSUE TITLE
KeyError when processing the callback handler of an inline message

### ISSUE THREAD

**Issue by kozalosev** [szastupov/aiotg#71]
Working on my bot, I encountered a problem. To illustrate it, I've written a simple script shown below:

```python
from aiotg import Bot, Chat, InlineQuery, CallbackQuery


bot = Bot(api_token="123456789:XXXXXXXXXXXXXXXXXXXXXXXXXX-YYYYYYYY", default_in_groups=True)

keyboard = {"inline_keyboard": [[{"callback_data": "clicked", "text": "Click me!"}]]}


@bot.command("/test")
def start(chat: Chat, match) -> None:
    chat.send_text("Hello!", reply_markup=bot.json_serialize(keyboard))


@bot.inline
def inline_query_handler(query: InlineQuery):
    query.answer([{
        "type": "article",
        "id": "0",
        "title": "Hello World",
        "description": "Testing...",
        "input_message_content": {"message_text": "Testing..."},
        "reply_markup": keyboard
    }])


@bot.callback
def callback_query_handler(chat: Chat, query: CallbackQuery) -> None:
    query.answer(text="Hello World")


if __name__ == '__main__':
    bot.run(debug=True)
```

_By the way, I think it's kind of inconsistent behavior that the `reply_markup` parameter of the `InlineQuery.answer()` method strictly takes a dict, but the `send_message()` method requires explicit JSON serialization._

It does 3 things:

1. responses to the `/test` command with a dummy message containing one inline button;
2. supports the inline mode, suggesting another dummy message with one inline button to the user;
3. handles button clicks identically, displaying a dummy text notification.

If we try to click on the button attached to the bot's message (either in the personal chat with bot itself or in a group chat), everything works fine. However, the click on the button of the user's message suggested by the bot, triggers a `KeyError`:

    Traceback (most recent call last):
      File "test_aiotg.py", line 30, in <module>
        bot.run(debug=True)
      File "/home/kozalo/venv/lib/python3.7/site-packages/aiotg/bot.py", line 157, in run
        run_with_reloader(loop, bot_loop, self.stop)
      File "/usr/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
        return future.result()
      File "/home/kozalo/venv/lib/python3.7/site-packages/aiotg/reloader.py", line 91, in run_with_reloader
        if isinstance(fut.result(), Event):
      File "/home/kozalo/venv/lib/python3.7/site-packages/aiotg/bot.py", line 131, in loop
        self._process_updates(updates)
      File "/home/kozalo/venv/lib/python3.7/site-packages/aiotg/bot.py", line 629, in _process_updates
        self._process_update(update)
      File "/home/kozalo/venv/lib/python3.7/site-packages/aiotg/bot.py", line 648, in _process_update
        coro = self._process_callback_query(update["callback_query"])
      File "/home/kozalo/venv/lib/python3.7/site-packages/aiotg/bot.py", line 613, in _process_callback_query
        chat = Chat.from_message(self, query["message"])
    KeyError: 'message'

The description of the `CallbackQuery` type in the official documentation says:

> If the button that originated the query was attached to a message sent by the bot, the field *message* will be present. If the button was attached to a message sent via the bot (in inline mode), the field *inline_message_id* will be present.

Therefore, callback queries issued by the messages sent by the user via inline mode don't have the `message` field, only an identificator of the inline message. Thus, it's not possible to instantiate a chat object from the missing message.

If it's OK to pass `None` instead of a `Chat` instance to the handler, then it's pretty easy to fix the issue:

```python
def _process_callback_query(self, query):
    chat = Chat.from_message(self, query["message"]) if "message" in query else None
    cq = CallbackQuery(self, query)
    for patterns, handler in self._callbacks:
        match = re.search(patterns, cq.data, re.I)
        if match:
            return handler(chat, cq, match)

    # make an assumption that the inline mode is mostly used in group chats
    if chat and not chat.is_group() or self.default_in_groups:
        return self._default_callback(chat, cq)
```

Otherwise, I cannot suggest an acceptable solution. Sorry.

**Comment by szastupov** [comment]
Sorry for taking so long to reply. I made a quick fix based on your solution, would you mind pulling in the last master and testing if it works for you?

**Comment by kozalosev** [comment]
Yes, this works fine for me. Thanks!
