### ISSUE TITLE
Handle text and commands at the same time

### ISSUE THREAD

**Issue by Podidiving** [szastupov/aiotg#80]
Hi! I think, this framework is great, and I use it sometimes.
Now I'm facing with next problem: I want my bot to have default text handler and also to have special handler for some commands 
For example, I have next code:

![image](https://user-images.githubusercontent.com/26285240/88288972-3408b700-ccfd-11ea-81a0-ded03783153f.png)

Now, if I'm sending my bot command ```/start```, but instead of ```handle_start_command``` callback, it will execute ```handle_text``` callback. What's the problem, and how to overcome it?

**Comment by szastupov** [comment]
Hey there! Thanks for the good words. Try using `@bot.default` decorator, instead of `@bot.handle("text")`, it should do what you want. Note that `default` passes you the whole json payload, so to extract text do something like:
```
@bot.default
def echo(chat, message):
    return chat.reply(message["text"])
```

**Comment by Podidiving** [comment]
Thanks! Now it's working :)
