### ISSUE TITLE
aiosocksy is deprecated and archived

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [szastupov/aiotg#82]
https://github.com/romis2012/aiosocksy is not maintained anymore and restricted to use `aiohttp<3.0`. It should be replaced with https://github.com/romis2012/aiohttp-socks.

**Comment by szastupov** [comment]
Dropped it completely, see https://github.com/szastupov/aiotg/commit/a4e8a28b8ea834e102a075b3db03078805be4dcf

But you can pass custom connector instead
